#!/usr/bin/env bash
# V5000 environment. This file is sourced by the verl child process.

export XMLIR_ENABLE_FAST_FC=${XMLIR_ENABLE_FAST_FC:-1}
export XFA_GEMM_TYPE=${XFA_GEMM_TYPE:-float16}
export XFA_BWD_USE_DS_SCALE=${XFA_BWD_USE_DS_SCALE:-1}
export CUDA_DEVICE_ORDER=${CUDA_DEVICE_ORDER:-OAM_ID}
export CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7}
export CUDA_DEVICE_MAX_CONNECTIONS=${CUDA_DEVICE_MAX_CONNECTIONS:-8}
export XMLIR_DIST_SINGLETON_STREAM=${XMLIR_DIST_SINGLETON_STREAM:-true}
export DIST_MULTI_STREAM=${DIST_MULTI_STREAM:-true}
export XMLIR_DIST_ASYNC_ISEND_IRECV=${XMLIR_DIST_ASYNC_ISEND_IRECV:-true}
export USE_FAST_BF16_FC=${USE_FAST_BF16_FC:-true}
export XMLIR_BATCH_PARALLEL=${XMLIR_BATCH_PARALLEL:-true}
export XPU_FORCE_SHARED_DEVICE_CONTEXT=${XPU_FORCE_SHARED_DEVICE_CONTEXT:-1}
export BKCL_TIMEOUT=${BKCL_TIMEOUT:-1800}
export BKCL_RDMA_PROXY_DISABLE=${BKCL_RDMA_PROXY_DISABLE:-1}
export BKCL_USE_AR=${BKCL_USE_AR:-1}
export BKCL_RING_OPT=${BKCL_RING_OPT:-1}
export BKCL_ENABLE_XDR=${BKCL_ENABLE_XDR:-1}
export CUDA_DISABLE_PRINTF=${CUDA_DISABLE_PRINTF:-1}
export XME_USE_LOCAL_TE=${XME_USE_LOCAL_TE:-true}
export XME_USE_TE_VERSION=${XME_USE_TE_VERSION:-1.13.0}
export XME_USE_CUSTOM_TRAINING_LOG=${XME_USE_CUSTOM_TRAINING_LOG:-true}
export PYTHONUNBUFFERED=1
export VERL_LOGGING_LEVEL=DEBUG

if [[ -n "${V5000_BASE_ENV:-}" ]]; then
    source "${V5000_BASE_ENV}"
fi
