#!/usr/bin/env bash
# Generic NVIDIA CUDA environment.

export CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7}
export CUDA_DEVICE_MAX_CONNECTIONS=${CUDA_DEVICE_MAX_CONNECTIONS:-1}
export HYDRA_FULL_ERROR=${HYDRA_FULL_ERROR:-1}
export MACA_PATH=${MACA_PATH:-/tmp}
export PYTHONUNBUFFERED=1
export VERL_LOGGING_LEVEL=DEBUG
